version: "3.8"
services:
  web:
    # We’ll set IMAGE via deploy.sh; for local dev this can also build.
    image: ${IMAGE:-yourdockeruser/dev:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
